server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  # 数据库
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/high-concurrency-seckill?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 20
      minimum-idle: 10

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
# springdoc-openapi项目配置
springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '秒杀测试'
      paths-to-match: '/**'
      packages-to-scan: com.shuishu.demo.seckill.controller